import json
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


class PortfolioQueueWorkerPoolAndMobileProjectTests(unittest.TestCase):
    def test_vps_scheduler_has_runtime_worker_pool_with_per_worker_guarded_interval(self):
        server = (ROOT / "server.py").read_text(encoding="utf-8")
        background = (ROOT / "firefox-extension" / "background.js").read_text(encoding="utf-8")

        self.assertIn("AUTONOMY_TICK_SECONDS = 5", server)
        self.assertIn("GLOBAL_CHATGPT_WORKER_LIMIT = 1", server)
        self.assertIn("MAX_CHATGPT_WORKERS = 8", server)
        self.assertIn("DYNAMIC_WORKER_SETTING_KEY = 'dynamic_worker_limit'", server)
        self.assertIn("DYNAMIC_CHATGPT_WORKERS = 1", server)
        self.assertIn("DYNAMIC_CLAUDE_WORKERS = 0", server)
        self.assertIn("DYNAMIC_CHATGPT_COOLDOWN_SECONDS = 120", server)
        self.assertIn("DYNAMIC_CLAUDE_COOLDOWN_SECONDS = 120", server)
        self.assertIn("DYNAMIC_WORKER_CHECK_INTERVAL_MS = 5000", server)
        self.assertIn("def set_dynamic_worker_settings(", server)
        self.assertIn("def set_dynamic_worker_limit(", server)
        self.assertIn("dynamic_provider_for_global_slot", server)
        self.assertIn("dynamic_provider_cooldown", server)
        self.assertIn("'/api/dynamic-workers'", server)
        self.assertIn("PORTFOLIO_AI_COOLDOWN_SECONDS = 120", server)
        self.assertIn("def portfolio_queue_allocate(", server)
        self.assertIn("def _global_dispatch_interval_due(", server)
        self.assertIn("def _worker_prompt_interval_due(", server)
        self.assertIn("Anti-spam is per dynamic worker", server)
        self.assertIn("def _autonomy_enqueue_worker_push(", server)
        self.assertIn("min_interval_seconds=max(5,int(min_interval_seconds or PORTFOLIO_AI_COOLDOWN_SECONDS))", server)
        self.assertIn("def global_worker_allocation(", server)
        self.assertIn("ai_global_slots", server)
        self.assertIn('status("awaiting-vps-dispatch", {reason: "cycle-finished"})', background)
        self.assertIn("setInterval(refreshTargets, 5000)", background)
        self.assertIn("pendingInitialDispatches", background)
        self.assertIn("forceInitialDispatch", background)
        self.assertIn("vpsDispatchOnly && !forceInitialDispatch", background)
        self.assertIn("(forceInitialDispatch || !vpsDispatchOnly)", background)
        self.assertIn("forceInitialDispatch = false", background)
        self.assertIn("draft && draft !== PROMPT && !forceInitialDispatch", background)
        self.assertIn('status("stale-draft-replaced", {reason: "forced-initial-dispatch"})', background)
        self.assertIn('if (forceInitialDispatch || draft === "" || draft === PROMPT)', background)
        self.assertIn("if latest and (bool(latest['generating']) or bool(latest['sending'])):", server)
        self.assertIn("if prompt_id and ready_id < prompt_id:", server)
        self.assertIn("A prompt from an older browser session must not permanently block", server)
        self.assertIn("latest_id <= prompt_id or latest_generating or latest_sending", server)
        self.assertNotIn('syncStatus("runner-auto-paused"', background)
        self.assertIn("WEAK_CYCLE_LIMIT = 4", background)
        self.assertIn("SHORT_CYCLE_MS = 15 * 1000", background)
        self.assertIn("repeated-short-or-null-result", background)
        self.assertIn("repeated-no-generation", background)
        self.assertIn('QUALITY_RETRY_LIMIT = "unbounded"', background)
        self.assertIn("quality-retry-scheduled", background)
        self.assertIn("same-assignment-non-stopping-execution-recovery", background)
        self.assertIn("DOE HET NU ECHT", background)
        self.assertIn("Geen audit, checklist, QA-overzicht, statusrapport", background)
        self.assertNotIn("hoogste beschikbare redeneerdiepte / High thinking", background)
        self.assertIn("ANDERE veilige uitvoeringsroute", background)
        self.assertIn("GA DOOR MET DE REST VAN DE ASSIGNMENT", background)
        self.assertIn("recoverableBlocker", background)
        self.assertIn("blockedResult || waitVps", background)
        self.assertIn("WAIT_HUMAN remains a real safety/dependency gate", background)
        self.assertIn("ensureHighThinking", background)
        self.assertIn('REQUIRED_THINKING_EFFORT = "high"', background)
        self.assertIn('data-testid="model-switcher-dropdown-button"', background)
        self.assertIn('aria-label="Model selector"', background)
        self.assertIn('THINKING_OPTION_SELECTOR', background)
        self.assertIn("think\\s+hard", background)
        self.assertIn("Selecting an option normally closes the Radix menu", background)
        self.assertIn('thinking-effort-high-verified', background)
        self.assertIn('thinking-effort-high-required', background)
        self.assertIn('const highReady = await ensureHighThinking()', background)
        self.assertIn('if (!highReady)', background)
        self.assertIn('"high-thinking-required|" + diagnostic', background)
        self.assertIn("compactThinkingDiagnostic", background)
        self.assertIn('MODEL_CONTROL_SELECTOR', background)
        self.assertIn('[role="menuitemradio"]', background)
        self.assertIn('[aria-haspopup="menu"]', background)
        self.assertIn('direct-control-selected', background)
        self.assertIn('controlHints', background)
        self.assertIn('function isHighLabel(value)', background)
        self.assertIn("missingQueueEvidence", background)
        self.assertIn("backend-non-stopping-dynamic-worker-policy", server)
        self.assertIn("Continue project autonomously with the next concrete implementation step", server)

    def test_production_policy_has_no_time_debounce_and_waits_for_generation_boundary(self):
        policy = json.loads((ROOT / "autonomy-policy.json").read_text(encoding="utf-8"))

        self.assertTrue(policy["default"]["auto_start"])
        self.assertEqual("vps", policy["default"]["dispatch_mode"])
        self.assertEqual(120, policy["default"]["min_ai_interval_seconds"])
        self.assertEqual(120, policy["default"]["continue_delay_seconds"])

        for project_id, project in policy["projects"].items():
            self.assertEqual("vps", project["dispatch_mode"], project_id)
            self.assertEqual(120, project["min_ai_interval_seconds"], project_id)
            self.assertEqual(120, project["continue_delay_seconds"], project_id)
            self.assertEqual(project_id != "ulab", project["auto_start"], project_id)

    def test_worker_prompt_uses_vps_sqlite_queue_and_evidence_done_gate(self):
        server = (ROOT / "server.py").read_text(encoding="utf-8")
        self.assertIn("portfolio_queue", server)
        self.assertIn("queue_backend':'sqlite'", server)
        self.assertIn("zCloud SQLite is de queue/source-of-truth", server)
        self.assertIn("Werk alleen aan deze assignment. Geen audit/status-only antwoord", server)
        self.assertIn("Bij een recoverable blocker: probeer in dezelfde cyclus een andere veilige route", server)
        self.assertIn("DONE alleen als alle completion criteria aantoonbaar gehaald zijn", server)
        self.assertIn("CONTINUE alleen na echte voortgang", server)
        self.assertIn("ZCLOUD_QUEUE_RESULT", server)
        self.assertIn("ZCLOUD_QUEUE_EVIDENCE", server)

    def test_global_worker_identity_follows_queue_owned_slot(self):
        server = (ROOT / "server.py").read_text(encoding="utf-8")
        self.assertIn("def _current_global_slot_map()", server)
        self.assertIn("Persist queue-owned portfolio slot identities exactly as assigned by SQLite", server)
        self.assertIn("'global_worker_slot':global_slot", server)
        self.assertIn("Portfolio Worker {global_slot}/{GLOBAL_CHATGPT_WORKER_LIMIT}", server)

    def test_browser_reports_queue_result_to_vps(self):
        background = (ROOT / "firefox-extension" / "background.js").read_text(encoding="utf-8")
        self.assertIn("ZCLOUD_QUEUE_ITEM:", background)
        self.assertIn("ZCLOUD_QUEUE_RESULT:", background)
        self.assertIn("ZCLOUD_QUEUE_EVIDENCE:", background)
        self.assertIn('"portfolio-queue-result"', background)
        self.assertIn("globalWorkerSlot", background)
        self.assertIn("nextTask", background)

    def test_terminal_markers_are_telemetry_only_and_workers_continue(self):
        background = (ROOT / "firefox-extension" / "background.js").read_text(encoding="utf-8")
        self.assertIn("Dynamic workers never stop themselves", background)
        self.assertIn('"WAIT_VPS"', background)
        self.assertIn('"WAIT_HUMAN"', background)
        self.assertIn('"COMPLETE"', background)
        self.assertIn('syncStatus("autonomy-continue"', background)
        self.assertIn("non-stopping-policy:", background)

    def test_mobile_projects_are_visible_and_touch_safe(self):
        index = (ROOT / "public" / "index.html").read_text(encoding="utf-8")
        app = (ROOT / "public" / "app.js").read_text(encoding="utf-8")
        css = (ROOT / "public" / "style.css").read_text(encoding="utf-8")

        self.assertIn('id="mobileProjectNav"', index)
        self.assertIn("if(mobileProjects)mobileProjects.innerHTML=", app)
        self.assertIn("(pointer: coarse)", app)
        self.assertIn('draggable="${draggable}"', app)
        self.assertIn(".mobile-project-nav{display:flex", css)
        self.assertIn(".mobile-project-nav a{min-height:44px", css)
        self.assertIn(".project-card-link{touch-action:manipulation}", css)


if __name__ == "__main__":
    unittest.main()
